
spring:
  data:
    mongodb:
      host: localhost
      database: cabApplication
      port: 27017 
  
#spring:
#  config:
#    import: configserver:http://localhost:8888
#    
#  application:
#    name: AssignedCabsTripsheet